### ISSUE TITLE
notepad xshm errors

### ISSUE THREAD

**Issue by matthiasclasen** [winepak/winepak#13]
I've installed notepad from the winepak repo, and it starts, but occasionally it gets BadValue X errors from XShmPutImage, particularly when halftiling or unmaximizing it (under gnome shell). This is using xwayland, but the X guys tell me that should be irrelevant.

**Comment by julianrichen** [comment]
Can you try updating your notepad++ install. I just pushed winepak/applications@28ab3b431a1ca279d484bd8aedc5faccd27c754b which uses pre-built binaries instead of the npp installer. I'm hoping that makes things more consistent since the npp installer seemed to give inconsistent results.

You might have to delete your old wineprefix:
```
rm -rf $HOME/.var/app/org.notepad_plus_plus.Notepad-plus-plus/wine
flatpak update org.notepad_plus_plus.Notepad-plus-plus
``

**Comment by julianrichen** [comment]
I'm closing this issue in-favor of winepak/applications#30 so application issues are on the application repo. If you can provide any more info, that issue would be best. Thanks.
